CREATE TABLE todos
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description TEXT,
    completed   BOOLEAN                                 NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_todos PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    enabled    BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email);

ALTER TABLE todos
    ADD CONSTRAINT FK_TODOS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- Index on user_id for faster todo queries
CREATE INDEX IF NOT EXISTS idx_todos_user_id ON todos(user_id);

-- Index on email for faster login queries
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- Index on username for faster JWT validation
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);